[package]
name = "simple-log"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
actix-web = "4"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"

[[bin]]
name = "the_milker"
path = "src/main_file_writing.rs"
